config/routes.rb
Rails.application.routes.draw do
  get 'search/on_call_caregivers' => 'search#OCC'
  get 'search/primary_caregivers' => 'search#PC'

  resources :appointments do
    put '/applications/:id/select' => 'appointments#select', as: :select
    resources :applications, only: [:new, :create]
    resources :reminders, only: [:create, :destroy]
  end
  resources :primary_caregivers do
    resources :appointments
    resources :patients, only: [:update]
  end

  resources :on_call_caregivers, only: [:show, :update, :edit] do
    get '/appointments' => 'appointments#confirmed_index', as: :confirmed_appointments
    get '/appointments/:id' => 'appointments#confirmed_show', as: :confirmed_appointment
    post '/send_email_to' => 'on_call_caregivers#send_email_to', as: :send_email_to
  end
  resources :primary_caregivers, only: [:show, :update, :edit]

  root 'welcome#index'

  resources :sessions, only: [:new, :create]

  resources :logins, only: [:create, :destroy, :new, :edit, :update]

  get 'login' => 'sessions'
  get 'logout'=> 'sessions#destroy'

  resources :twilio, only: [:new, :create, :destroy]
  get 'twilio' => 'twilio#new'
  post '/send_sms' =>'twilio#send_sms'

  resources :mail, only: [:new, :create, :destroy]
  get 'mail' => 'mail#new'
  post '/send_email' => 'mail#send_email'
  post '/send_confirmation' => 'mail#send_confirmation'

end

app/models/primary_caregiver.rb
class PrimaryCaregiver < ActiveRecord::Base
  has_merit

  has_one :login, :as => :loginable
  has_many :caregiver_relationships
  has_one :patient
  has_many :appointments, through: :caregiver_relationships
  has_attached_file :image, styles: { medium: "300x300>", thumb: "160x160#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def find_OCC(miles)
    Login.near([login.latitude, login.longitude], miles).where(loginable_type: "OnCallCaregiver")
  end

end

app/controllers/primary_caregivers_controller.rb
class PrimaryCaregiversController < ApplicationController
  def edit
    @pcc = PrimaryCaregiver.find_by(id: params[:id])
  end


  def update
    pcc = PrimaryCaregiver.find_by(id: params[:id])
    pcc.update_attributes(pcc_params)
    if pcc.save
      redirect_to root_path
    else
      redirect_to primary_caregiver_path(primary_caregiver.id)
    end
  end

  def show
    @caregiver = PrimaryCaregiver.find_by(id: params[:id])
  end

  private
    def pcc_params
      params.require(:primary_caregiver).permit(:about_me, :image)
    end
end

app/views/primary_caregivers/edit.html.erb
<div>
  <% if @pcc.errors.any? %>
  <% @pcc.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
</div>
<div class="user-primary-container">
<div class="user-form-container row">
<h1> Edit Profile:</h1>
  <div class="col-md-6">
    <h2>Update Profile Information</h2>
    <%= form_for @pcc.login, method: :patch do |f| %>
    <div class="form-group">
      <%= f.label :First_Name %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :Last_Name %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :Address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :City %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>

   <div class="form-group">
          <%= f.label :State %>
         <%= f.select :state, [
          ['Alabama', 'AL'],
          ['Alaska', 'AK'],
          ['Arizona', 'AZ'],
          ['Arkansas', 'AR'],
          ['California', 'CA'],
          ['Colorado', 'CO'],
          ['Connecticut', 'CT'],
          ['Delaware', 'DE'],
          ['District of Columbia', 'DC'],
          ['Florida', 'FL'],
          ['Georgia', 'GA'],
          ['Hawaii', 'HI'],
          ['Idaho', 'ID'],
          ['Illinois', 'IL'],
          ['Indiana', 'IN'],
          ['Iowa', 'IA'],
          ['Kansas', 'KS'],
          ['Kentucky', 'KY'],
          ['Louisiana', 'LA'],
          ['Maine', 'ME'],
          ['Maryland', 'MD'],
          ['Massachusetts', 'MA'],
          ['Michigan', 'MI'],
          ['Minnesota', 'MN'],
          ['Mississippi', 'MS'],
          ['Missouri', 'MO'],
          ['Montana', 'MT'],
          ['Nebraska', 'NE'],
          ['Nevada', 'NV'],
          ['New Hampshire', 'NH'],
          ['New Jersey', 'NJ'],
          ['New Mexico', 'NM'],
          ['New York', 'NY'],
          ['North Carolina', 'NC'],
          ['North Dakota', 'ND'],
          ['Ohio', 'OH'],
          ['Oklahoma', 'OK'],
          ['Oregon', 'OR'],
          ['Pennsylvania', 'PA'],
          ['Puerto Rico', 'PR'],
          ['Rhode Island', 'RI'],
          ['South Carolina', 'SC'],
          ['South Dakota', 'SD'],
          ['Tennessee', 'TN'],
          ['Texas', 'TX'],
          ['Utah', 'UT'],
          ['Vermont', 'VT'],
          ['Virginia', 'VA'],
          ['Washington', 'WA'],
          ['West Virginia', 'WV'],
          ['Wisconsin', 'WI'],
          ['Wyoming', 'WY']
        ] %>
        </div>
        <div class="form-group">
          <%= f.label :Phone %>
          <%= f.text_field :phone, class: 'form-control' %>
        </div>
        <div class="form-group">
         <%= f.label :Zipcode %>
         <%= f.text_field :zipcode, class: 'form-control' %>
        </div>
       <div class="form-group">
         <%= f.label :Email %>
         <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
         <%= f.label :Password_Confirmation %>
         <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <button type="button" class="btn btn-primary">
          <%= f.submit "Save Profile", class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <h2>Update Patient Information</h2>
      <%= form_for [@pcc, @pcc.patient], method: :put do |f| %>

    <div class="form-group">
       <%= f.label :Patient_Name %>
       <%= f.text_field :name, class: 'form-control' %>
      </div>

    <div class="form-group">
       <%= f.label :Patient_gender %>
       <%= f.select :gender, [
        ['Male', 'male'],
        ['Female', 'female']] %>
    </div>

    <div class="form-group">
       <%= f.label :Patient_habits %>
       <%= f.text_field :habits, class: 'form-control' %>
    </div>

    <div class="form-group">
       <%= f.label :Patient_Routine %>
       <%= f.text_field :routine, class: 'form-control' %>
    </div>

    <div class="form-group">
       <%= f.label :Patient_ailments %>
       <%= f.text_field :ailments, class: 'form-control' %>
    </div>

    <div class="form-group">
       <%= f.label :Patient_medication %>
       <%= f.text_field :medication, class: 'form-control' %>
    </div>

    <div class="form-group">
       <%= f.label :Patient_background %>
       <%= f.text_field :background, class: 'form-control' %>
    </div>

    <div class="form-group">
       <%= f.label :Patient_age %>
       <%= f.text_field :age, class: 'form-control' %>
    </div>

    <div class="form-group">
       <%= f.label :Patient_hobbies %>
       <%= f.text_field :hobbies, class: 'form-control' %>
    </div>

    <div>
    <div class="form-group">
      <button type="button" class: "btn btn-primary"%>
       <%= f.submit "Save Patient Profile", class: "btn btn-primary" %>
       <%end%>
      </div>
      </button>

      </div>
    </div>
  </div>
  </div>
  <div class="user-form-container about-me-edit">
  <div class="form-group">
    <h2>Update About Me</h2>
    <%= form_for @pcc do |f| %>
     <div class="form-group">
       <%= f.label :About_Me %>
       <%= f.text_area :about_me, class: 'form-control' %>
       <div class="form-group">
       <%= f.label :image %>
       <%= f.file_field :image, class: 'form-control' %><br>
      </div>
     </div>
      <br>

      <div class="form-group">
        <button type="button" class="btn btn-primary">
       <%= f.submit "Save About Me & Image", class: "btn btn-primary"%>
      <% end %>
    </button>
     </div>
</div>
</div>
</div>

app/views/primary_caregivers/show.html.erb
<div class="show-container">
  <div class="row">
    <!-- left column -->
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center">
        <p id="profile-pic"><%= image_tag @caregiver.image(:thumb), :class => "img-circle img-thumbnail img-responsive"%></p>
      </div>
    </div>
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
        <div class="about">
          <h2 class="page-header">Profile Page</h2>
      <h2 class="profile-subheader">About Me</h2>
      <h3>Summary</h3>
      <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Show</button>
      <div id="demo" class="collapse">
      <p><%= @caregiver.about_me %></p>
    </div>
    <div class="patient-info">
    <h2 class="profile-subheader">Patient Overview</h2>
      <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#patients">Show</button>
      <div id="patients" class="collapse">
      <h3>Patient Name</h3>
      <div><p><%= @caregiver.patient.name %></p></div>
      <h3>Patient Age</h3>
      <div><p><%= @caregiver.patient.age %></p></div>
      <h3>Patient Gender</h3>
      <div><p><%= @caregiver.patient.gender %></p></div>
      <h3>Patient Ailments</h3>
      <div><p><%= @caregiver.patient.ailments %></p></div>
      <h3>Patient Hobbies</h3>
      <div><p><%= @caregiver.patient.hobbies %></p></div>
      <h3>Patient Background</h3>
      <div><p><%= @caregiver.patient.background %></p></div>
      </div>
    </div>
    </div>
  </div>
</div>

  <div class="appointments" id="calendar">
    <%= month_calendar events: @caregiver.appointments do |date, appointments| %>
    <%= date %>
    <% appointments.each do |appointment| %>
        <div>
          Needs Caretaking!
          <%= link_to 'Apply To Help', new_appointment_application_path(appointment) %>
        </div>
        <% end %>
    <% end %>
  </div>
</div>