config/routes.rb
Rails.application.routes.draw do
  get 'search/on_call_caregivers' => 'search#OCC'
  get 'search/primary_caregivers' => 'search#PC'

  resources :appointments do
    put '/applications/:id/select' => 'appointments#select', as: :select
    resources :applications, only: [:new, :create]
    resources :reminders, only: [:create, :destroy]
  end
  resources :primary_caregivers do
    resources :appointments
    resources :patients, only: [:update]
  end

  resources :on_call_caregivers, only: [:show, :update, :edit] do
    get '/appointments' => 'appointments#confirmed_index', as: :confirmed_appointments
    get '/appointments/:id' => 'appointments#confirmed_show', as: :confirmed_appointment
    post '/send_email_to' => 'on_call_caregivers#send_email_to', as: :send_email_to
  end
  resources :primary_caregivers, only: [:show, :update, :edit]

  root 'welcome#index'

  resources :sessions, only: [:new, :create]

  resources :logins, only: [:create, :destroy, :new, :edit, :update]

  get 'login' => 'sessions'
  get 'logout'=> 'sessions#destroy'

  resources :twilio, only: [:new, :create, :destroy]
  get 'twilio' => 'twilio#new'
  post '/send_sms' =>'twilio#send_sms'

  resources :mail, only: [:new, :create, :destroy]
  get 'mail' => 'mail#new'
  post '/send_email' => 'mail#send_email'
  post '/send_confirmation' => 'mail#send_confirmation'

end

app/models/on_call_caregiver.rb
class OnCallCaregiver < ActiveRecord::Base
  has_merit

  has_many :caregiver_relationships
  has_many :appointments, through: :caregiver_relationships
  has_one :login, :as => :loginable
  has_many :badges
  has_attached_file :image, styles: { medium: "300x300>", thumb: "160x160#" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  def find_PC(miles)
    Login.near([login.latitude, login.longitude], miles).where(loginable_type: "PrimaryCaregiver")
  end
end

app/controllers/on_call_caregivers_controller.rb
class OnCallCaregiversController < ApplicationController
  def edit
    @occ = OnCallCaregiver.find_by(id: params[:id])
  end

  def update
    @occ = OnCallCaregiver.find_by(id: params[:id])
    @occ.update_attributes(occ_params)
    if @occ.save
      redirect_to root_path
    else
      redirect_to on_call_caregiver_path(on_call_caregiver.id)
    end
  end

  def show
    @caregiver = OnCallCaregiver.find_by(id: params[:id])
  end

  def send_email_to
    occ = OnCallCaregiver.find_by(id: params[:on_call_caregiver_id])
    pc = current_user.loginable
    OnCallCaregiverMailer.send_email_to(occ, pc, params[:message]).deliver
    flash[:notice] = "You sent your message to Caregiver " + pc.login.full_name
    redirect_to on_call_caregiver_path(occ)
  end

  private
    def occ_params
      params.require(:on_call_caregiver).permit(:education, :credentials, :about, :specialities, :experience, :hobbies, :image)
    end
end

app/views/on_call_caregivers/edit.html.erb
<div>
  <% if @occ.errors.any? %>
  <% @occ.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
</div>

<div class="occ-edit">
<div class="col-md-6">
<h1> Edit Profile:</h1>
<h3> <%= form_for @occ do |f| %>
  <div class="form-group">
    <%= f.label :Education %>
    <%= f.text_field :education %>
  </div>
  <div class="form-group">
    <%= f.label :About %>
    <%= f.text_field :about %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :Credentials %>
    <%= f.text_field :credentials %>
  </div>
  <div class="form-group">
    <%= f.label :Specialty %>
    <%= f.text_field :specialities %>
  </div>
  <div class="form-group">
    <%= f.label :Experience %>
    <%= f.text_area :experience %>
  </div>
  <div class="form-group">
    <%= f.label :Hobbies %>
    <%= f.text_area :hobbies %>
  </div>



<%= f.submit "Update Profile"%>
  <% end %>
</div>
</div>
</div>

app/views/on_call_caregivers/show.html.erb
<div class="on-call-show">
<div id="profile-show">
  <div class="basic-info">
  <%=render :partial=> 'caregivers/login_info', locals: {caregiver: @caregiver}%>
  </div>
<div class="profile-tabs row">
  <ul class="nav-tabs">
    <li class="active"><a data-toggle="tab" href="#about">About Me</a></li>
    <li><a data-toggle="tab" href="#background-info">My Background</a></li>
    <li><a data-toggle="tab" href="#contact">Contact Me</a></li>
  </ul>
</div>
  <div class="tab-content">
    <div id="about" class="tab-pane fade in active">
      <h3 class="sub-profile-header">Summary</h3>
      <p><%= @caregiver.about %></p>
      <h3 class="sub-profile-header">Hobbies</h3>
      <p><%= @caregiver.hobbies %></p>
    </div>

    <div id="background-info" class="tab-pane">
      <h3 class="sub-profile-header">Relevant Caretaking Experience</h3>
      <p><%= @caregiver.experience %></p>
      <h3 class="sub-profile-header">Education</h3>
      <p><%= @caregiver.education %></p>
      <h3 class="sub-profile-header">Credentials</h3>
      <p><%= @caregiver.credentials %></p>
      <h3 class="sub-profile-header">Specialties</h3>
      <p><%= @caregiver.specialities %></p>

      <div id= "badge-count">
        <p>You have <%= current_user.loginable.badges.count %> badges. Help more people to receive badges and become CERTIFIED."</p>
        <ul>
          <% current_user.loginable.badges.each do |badge| %>
            <li><%= badge.name %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div id="contact" class="tab-pane">
      <%= form_tag on_call_caregiver_send_email_to_path(@caregiver) do %>
        <%= text_area_tag :message, "", rows: 5, class: "form-control" %>
        <%= submit_tag 'Send Personal Message', class: "btn btn-primary form-control contact-submit" %>
      <% end %>
    </div>
  </div>
</div>
</div>