config/routes.rb
Rails.application.routes.draw do
  get 'search/on_call_caregivers' => 'search#OCC'
  get 'search/primary_caregivers' => 'search#PC'

  resources :appointments do
    put '/applications/:id/select' => 'appointments#select', as: :select
    resources :applications, only: [:new, :create]
    resources :reminders, only: [:create, :destroy]
  end
  resources :primary_caregivers do
    resources :appointments
    resources :patients, only: [:update]
  end

  resources :on_call_caregivers, only: [:show, :update, :edit] do
    get '/appointments' => 'appointments#confirmed_index', as: :confirmed_appointments
    get '/appointments/:id' => 'appointments#confirmed_show', as: :confirmed_appointment
    post '/send_email_to' => 'on_call_caregivers#send_email_to', as: :send_email_to
  end
  resources :primary_caregivers, only: [:show, :update, :edit]

  root 'welcome#index'

  resources :sessions, only: [:new, :create]

  resources :logins, only: [:create, :destroy, :new, :edit, :update]

  get 'login' => 'sessions'
  get 'logout'=> 'sessions#destroy'

  resources :twilio, only: [:new, :create, :destroy]
  get 'twilio' => 'twilio#new'
  post '/send_sms' =>'twilio#send_sms'

  resources :mail, only: [:new, :create, :destroy]
  get 'mail' => 'mail#new'
  post '/send_email' => 'mail#send_email'
  post '/send_confirmation' => 'mail#send_confirmation'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommuniCare</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <script src = "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.0/moment.min.js">
  </script>
  <script src = "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.0/fullcalendar.min.js">
  </script>
  <link href='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.0/fullcalendar.min.css' rel= "stylesheet" />
  <link href= "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.0/fullcalendar.print.css"
  rel= "stylesheet" />
  <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Noto+Serif' rel='stylesheet' type='text/css'>

</head>
<body>
  <nav>
  <%if !logged_in? %>

  <ul class="nav nav-pills navbar-static-top">
  <li id="app-title"> CommuniCare </li>
  <li><%= link_to 'Home', root_path %></li>
  <li role="presentation"><%= link_to 'Sign Up', new_login_path%></li>
  <li role="presentation"><%= link_to 'Login', new_session_path %></li>
  <li role="presentation"><a href="#">About</a></li>
  </ul>
    <% else %>
      <% if current_user.loginable_type == "PrimaryCaregiver" %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills navbar-static-top">
      <li id="app-title"> CommuniCare </li>
        <li><%= link_to 'Home', root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Show Profile',primary_caregiver_path(current_user.loginable) %></li>
            <li><%= link_to 'Edit Profile', edit_primary_caregiver_path(current_user.loginable) %></li>
          </ul>
        </li>
        <li><%= link_to 'Appointments', primary_caregiver_appointments_path(current_user.loginable) %></li>
          <li id="search-bar-caregiver">Search in your area for caregivers:
        <%= form_tag :search_on_call_caregivers, method: :get do %>
          <%= select_tag :distance, options_for_select([["5 Miles",5], ["10 Miles",10], ["20 Miles",20], ["50 Miles",50], ["100 Miles",100]])%>
        <%= submit_tag "Search", class: "btn btn-default" %>
        <% end %></li>
          <li id= "sign-out-nav"><%= link_to 'Sign Out', logout_path %></li>
        </li>
        <div id="welcome-user">Welcome, <%= current_user.email %></div>
      </ul>

        <% else %>
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills navbar-static-top">
        <li id="app-title"> CommuniCare </li>
        <li><%= link_to 'Home', root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Show Profile',on_call_caregiver_path(current_user.loginable) %></li>
            <li><%= link_to 'Edit Profile', edit_on_call_caregiver_path(current_user.loginable) %></li>
          </ul>
        </li>
        <li><%= link_to 'Scheduled Appointments', on_call_caregiver_confirmed_appointments_path(current_user.loginable) %></li>
        <li id="search-bar-caregiver">Search in your area for caregivers:
          <%= form_tag :search_primary_caregivers, method: :get do %>
          <%= select_tag :distance, options_for_select([["5 Miles",5], ["10 Miles",10], ["20 Miles",20], ["50 Miles",50], ["100 Miles",100]]) %>
        <%= submit_tag "Search", class: "btn btn-default"  %>
        <% end %>
      </li>
      <li id= "sign-out-nav"><%= link_to 'Sign Out', logout_path %></li>
      </li>
        <div id="welcome-user">Welcome, <%= current_user.email %></div>
      </ul>
        <% end %>
      </ul>
    <% end %>

  </nav>

  <div id="flash-container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
      <% end %>
    <% end %>
  </div>



  <div id="yield">
    <%= yield %>
  </div>



</body>

</html>

app/views/layouts/confirm_occ.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Hello from Communicare, <%= @occ.login.full_name %></h1>
    <p>
      Your application has been selected by <%= @pc.login.full_name%>.
    </p>
    <p>
      To see the details log in and go to: <%= @url %>.
    </p>
    <p>Thanks for using Communicare!</p>
  </body>
</html>